import type { Metadata } from "next";
import { Inter, Koulen } from "next/font/google";
import "./globals.css";

const koulen = Koulen({
  weight: ['400'],
  style: ['normal'],
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={koulen.className}>{children}</body>
    </html>
  );
}
