import type { Metadata } from "next";
import { Inter, Koulen } from "next/font/google";
import "./globals.css";
import Header from "@/components/organisms/header/Header";

const koulen = Koulen({
  weight: ['400'],
  style: ['normal'],
  subsets: ['latin']
});

const inter = Inter({
  weight: ['400', '500'],
  style: ['normal'],
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: "Maarten Skulls",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <style>
          {`
            :root {
              --font-inter: ${inter.style.fontFamily};
              --font-koulen: ${koulen.style.fontFamily};
          `}
        </style>
      </head>
      <body className={koulen.className}>
        <Header/>
        {children}
      </body>
    </html>
  );
}
